title: Callouts
author: Cody
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is just site to test potential callouts.

twitter_username: #
github_username:  #

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
